"""a description

Revision ID: 019e518a0f49
Revises: 
Create Date: 2024-06-27 14:18:29.750490

"""
from typing import Sequence, Union
import apps.openai.internal.db

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019e518a0f49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('meta', apps.openai.internal.db.JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_store',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('meta', apps.openai.internal.db.JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_store_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('meta', apps.openai.internal.db.JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_store_file')
    op.drop_table('vector_store')
    op.drop_table('file_content')
    op.drop_table('file')
    # ### end Alembic commands ###
