"""a description

Revision ID: 92ed67a671af
Revises: 
Create Date: 2024-06-28 15:59:16.000487

"""
from typing import Sequence, Union
import apps
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ed67a671af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_details', sa.Text(), nullable=True),
    sa.Column('meta', apps.openai.internal.db.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_store',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('last_active_at', sa.BigInteger(), nullable=False),
    sa.Column('meta', apps.openai.internal.db.JSONField(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('usage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_after_anchor', sa.Text(), nullable=True),
    sa.Column('expires_after_days', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('file_counts_in_progress', sa.BigInteger(), nullable=False),
    sa.Column('file_counts_completed', sa.BigInteger(), nullable=False),
    sa.Column('file_counts_failed', sa.BigInteger(), nullable=False),
    sa.Column('file_counts_cancelled', sa.BigInteger(), nullable=False),
    sa.Column('file_counts_total', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_store_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('meta', apps.openai.internal.db.JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_content')
    op.drop_table('vector_store_file')
    op.drop_table('vector_store')
    op.drop_table('file')
    # ### end Alembic commands ###
