"""a description

Revision ID: 96f2b931c2fe
Revises: 
Create Date: 2024-06-27 15:50:05.173427

"""
from typing import Sequence, Union
from apps.openai.internal.db import JSONField
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f2b931c2fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('meta', JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_store',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('meta', JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vector_store_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('meta', JSONField(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_store_file')
    op.drop_table('vector_store')
    op.drop_table('file_content')
    op.drop_table('file')
    # ### end Alembic commands ###
