"""a description

Revision ID: bf26a3fe9e79
Revises: 96f2b931c2fe
Create Date: 2024-06-27 16:09:45.416256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf26a3fe9e79'
down_revision: Union[str, None] = '96f2b931c2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_content', 'content',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.create_foreign_key(None, 'file_content', 'file', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_content', type_='foreignkey')
    op.alter_column('file_content', 'content',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
